//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senao_EE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.WorkOvertime = new HashSet<WorkOvertime>();
        }
    
        public int EmployeeSN { get; set; }
        public int DepartmentSN { get; set; }
        public string Name { get; set; }
        public string ID { get; set; }
        public string PhoneNumber { get; set; }
        public int Status { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<WorkOvertime> WorkOvertime { get; set; }
    }
}
