//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senao_EE
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_WorkOvertime
    {
        public string DepartmentName { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeID { get; set; }
        public string Reason { get; set; }
        public Nullable<double> Hours { get; set; }
        public string DateFrom { get; set; }
        public string TimeFrom { get; set; }
        public string DateTo { get; set; }
        public string TimeTo { get; set; }
        public string UpdateTime { get; set; }
        public Nullable<int> DepartmentSN { get; set; }
        public int WorkOvertimeSN { get; set; }
        public System.DateTime OrgFrom { get; set; }
        public string InsertTime { get; set; }
    }
}
