//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Senao_EE
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOvertime
    {
        public int WorkOvertimeSN { get; set; }
        public int EmployeeSN { get; set; }
        public System.DateTime TimeFrom { get; set; }
        public System.DateTime TimeTo { get; set; }
        public string Reason { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
